version: "2"

services:

  nginx:
    build: ./docker-service/nginx
    volumes_from:
      - source_code
    ports:
      - 80:80
      - 443:443
#    volumes:
#      - ./docker-service/nginx/config.d:/etc/nginx
    depends_on:
      - php_fpm
    networks:
      app_net:
        ipv4_address: 172.16.238.11

  php_fpm:
    build: ./docker-service/php-fpm
    volumes_from:
      - source_code
    volumes:
      - ./docker-service/php-fpm/config.d:/usr/local/etc/php/
    links:
      - db
      - memcached
    expose:
      - 9000
#    extra_hosts:
#      - "admin.kf5.co:172.16.238.11"
#      - "b.kf5.co:172.16.238.11"
#      - "pusher-new.kf5.com:172.16.238.16"
#      - "els-center.kf5.com:172.16.238.11"
    networks:
      app_net:
        ipv4_address: 172.16.238.12

  db:
    build: ./docker-service/db
#    restart: always
    volumes:
      - ./docker-service/db/config.d:/etc/mysql/mysql.conf.d/
      - ./docker-service/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    expose:
      - 3306
    ports:
      - 33061:3306
    networks:
      app_net:
        ipv4_address: 172.16.238.13

  memcached:
    build: ./docker-service/memcached
#    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.14

  rabbitmq:
    build: ./docker-service/rabbitmq
#    restart: always
    hostname: test-rabbit
    volumes:
      - ./docker-service/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@test-rabbit
    expose:
      - 5672
    ports:
      - 8902:15672
    networks:
      app_net:
        ipv4_address: 172.16.238.17

  redis:
    build: ./docker-service/redis
    expose:
      - 6379
    volumes:
      - ./docker-service/redis/data:/data
    networks:
      app_net:
        ipv4_address: 172.16.238.21

  source_code:
    image: nginx:stable
    volumes:
      - ./www:/var/www/html
    command: "true"

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1