FROM memcached:latest

#RUN echo "Asia/Chongqing" > /etc/timezone && \
#    apt-get update && apt-get install -y \
#    iputils-ping \
#    libnet-ifconfig-wrapper-perl \
#    ntpdate \
#    libconfig-crontab-perl